### ISSUE TITLE
Vue Axios endpoints

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [Tobiasmidskards/wecode#1]
All axios endpoints has this format /ideazer/public/api/idea/ where /ideazer/public is someting local to the Tobias. This breaks all other enviroments.

Should just have the format /api/idea

**Comment by Tobiasmidskards** [comment]
Problems of the root document folder on the XAMPP stack, caused me to prefix my local enviroment. 
Issue is fixed and closed.
