### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [Tobiasmidskards/wecode#2]
You missed a key part in Laravel, and that is database migrations, so i can get the same database as you! This is all done through migration files. Have a look here
https://laravel.com/docs/5.7/migrations

Solution: make the right migration for Idea.php

tip: run 'php artisan migrate:fresh' to make sure that your migrations work when building from scratch 😄

**Comment by Tobiasmidskards** [comment]
I totally missed the point there! 
The migration is absolute important.

Recently worked with Maven and databases at school. Maven makes it so easy for me and my classmates, when switching to other enviroments. Here it is indeed very important that you write the SQL statements for creation of the tables!

Migration is up!
