### ISSUE TITLE
Code improvement tip

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [Tobiasmidskards/wecode#3]
Laravel does a lot of heavy lifting for you, and that is what makes it so powerfull!

So take you function update() in IdeaController.php L70.
Here you are manually and for each column filling the model from the request like this:

        $idea->title = $request->input('title');
        $idea->body = $request->input('body');
        // committer.
        $idea->save();
This can be done in a one liner like this

        $idea->update($request->all());

these things comes from experience working with code and the framework.

 Solution: Try and take your store method in the same controller, and clean it up a bit.
Look here for help https://laravel.com/docs/5.7/eloquent#mass-assignment

**Comment by Tobiasmidskards** [comment]
The `->update` is neat!

Regarding the store method, I added the $fillable property in my model. It works good for `$idea->fill($request->all());`, but then i want to assign it to the right user. Therefore i do a `$idea->user_id = auth()->user()->id;` before i commit.
